# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Cengiz Henk
tagline:          'Neugieriger Informatiker'
description:      'Als neugieriger Informatiker mit einer Leidenschaft für Naturwissenschaften bin ich stets bestrebt, komplexe Herausforderungen anzugehen und durch kreative Lösungen positive Veränderungen zu bewirken.'
url:              https://cengizhenk.github.io
baseurl:          /cengizhenk.github.io

author:
  name:           'Cengiz Henk'
  url:            https://cengizhenk.github.io

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/CengizHenk/CengizHenk.github.io
